

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle all routes with Next.js (this is usually handled by the plugin-nextjs)
# Keeping it for now, but might be redundant.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# Specific redirects for critical paths
[[redirects]]
  from = "/profile"
  to = "/dashboard/profile"
  status = 301
  force = true

[[redirects]]
  from = "/settings"
  to = "/dashboard/settings"
  status = 301
  force = true

# API proxy for local development (netlify dev)
# This rule is only active when `netlify dev` is used and conditions are met.
# It should NOT interfere with production.
[[redirects]]
  from = "/api/*" 
  to = "http://localhost:8080/api/:splat"
  status = 200
  force = false # Typically false for conditional redirects
  conditions = {Role = ["anonymous"], Environment = ["development"]} # Example conditions

# Proper 404 handling (usually handled by Next.js)