services:
  - type: web
    name: practicegenius-api
    env: docker
    region: oregon
    plan: free
    
    # Docker settings
    dockerContext: .
    dockerfile: Dockerfile
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: '*'
      - key: FRONTEND_URL
        value: 'https://practicegeniusv2.netlify.app'
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: '0'  # Only for development, remove in production with valid certificates
      - key: LOG_LEVEL
        value: 'debug'
      - key: NODE_ENV
        value: 'production'
    
    # Health check settings
    healthCheckPath: /
    healthCheckTimeout: 30s
    healthCheckInterval: 60s
    healthCheckThreshold: 3
    
    # Auto-deploy settings
    autoDeploy: true
