services:
  - type: web
    name: practicegenius-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Health check settings - accept any path
    healthCheckPath: /
    healthCheckTimeout: 30s
    healthCheckInterval: 60s
    healthCheckThreshold: 3
